Store/Store.APP/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Mvc;

namespace Store.APP.Areas.Admin.Controllers;

[Area("Admin")]
public class DashboardController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Store/Store.APP/Components/ProductSummaryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Store.Repositories;
using Store.Services.Contracts;

namespace Store.APP.Components;

public class ProductSummaryViewComponent : ViewComponent
{
    private readonly IServiceManager _serviceManager;

    public ProductSummaryViewComponent(IServiceManager serviceManager)
    {
        _serviceManager = serviceManager;
    }

    public string Invoke()
    {
        return _serviceManager.ProductService.GetAllProducts(false).Count().ToString();
    }
}

Store/Store.APP/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Repositories.Contracts;

namespace Store.APP.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IRepositoryManager _repositoryManager;

        public CategoryController(IRepositoryManager repositoryManager)
        {
            _repositoryManager = repositoryManager;
        }
        
        // GET: CategoryController
        public ActionResult Index()
        {
            var model = _repositoryManager.Category.FindAll(false);
            return View(model);
        }

    }
}

Store/Store.APP/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Repositories;
using Store.Repositories.Contracts;
using Store.Services.Contracts;

namespace Store.APP.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index()
        {
            var model = _serviceManager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var product = _serviceManager.ProductService.GetOneProduct(id, false);
            return View(product);
        }


    }
}

Store/Store.APP/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Store.APP</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/Store.APP.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <partial name="_Navbar"/>
    @RenderSection("Header", false)
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<footer>
    @RenderSection("Footer", false)
    Footer
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Store/Store.APP/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-dark bg-dark border-bottom navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand text-white" href="/">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup"
                aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between" id="navbarNavAltMarkup">
            
            <ul class="navbar-nav flex-grow-1">
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-action="Index" asp-controller="Dashboard">Home</a>    
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-action="Index" asp-controller="Product">Products (@await Component.InvokeAsync("ProductSummary"))</a>    
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" aria-current="page" asp-action="Index" asp-controller="Category">Categories</a>    
                </li>
            </ul>
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a target="_blank" class="nav-link text-white" aria-current="page" asp-area="" asp-action="Index" asp-controller="Home">Home</a>
                </li>  
            </ul>
        </div>
    </div>
</nav>