Store/Store.APP/Models/Product.cs
namespace Store.APP.Models;

public class Product
{
    public int Id { get; set; }
    public string? Name { get; set; } = string.Empty;
    public decimal Price { get; set; }
}

Store/Store.APP/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Store.Entities.Dtos;
using Store.Entities.Models;
using Store.Services.Contracts;

namespace Store.APP.Areas.Admin.Controllers;

[Area("Admin")]
public class ProductController : Controller
{
    private readonly IServiceManager _serviceManager;

    public ProductController(IServiceManager serviceManager)
    {
        _serviceManager = serviceManager;
    }

    public IActionResult Index()
    {
        var model = _serviceManager.ProductService.GetAllProducts(false);
        return View(model);
    }

    public IActionResult Create()
    {
        ViewBag.Categories = GetCategoriesSelectList();
        return View();
    }

    private SelectList GetCategoriesSelectList()
    {
        return new SelectList( _serviceManager.CategoryService.GetAllCategories(false),"Id", "Name", "1");
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([FromForm] ProductDtoForInsertion productDtoForInsertion, IFormFile file)
    {
        if (ModelState.IsValid)
        {
            //file operation
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot","images", file.FileName);
            using(var  stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            
            productDtoForInsertion.ImageUrl = string.Concat("/images/", file.FileName);
            _serviceManager.ProductService.CreateProduct(productDtoForInsertion);
            return RedirectToAction("Index");
        }
        return View();
    }

    public IActionResult Update([FromRoute(Name = "id")] int id)
    {
        ViewBag.Categories = GetCategoriesSelectList();
        var model = _serviceManager.ProductService.GetOneProductForUpdate(id, false);
        return View(model);
    }
    
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Update([FromForm] ProductDtoForUpdate productDto, IFormFile file)
    {
        if (ModelState.IsValid)
        {
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot","images", file.FileName);
            using(var  stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }
            
            productDto.ImageUrl = string.Concat("/images/", file.FileName);
            _serviceManager.ProductService.UpdateOneProduct(productDto);
            return RedirectToAction("Index");
        }
        
        return View();
    }

    public IActionResult Delete([FromRoute(Name = "id")] int id)
    {
        _serviceManager.ProductService.DeleteOneProduct(id);
        return RedirectToAction("Index");
    }
}

Store/Store.APP/Components/CategoriesMenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Store.Services.Contracts;

namespace Store.APP.Components;

public class CategoriesMenuViewComponent : ViewComponent
{
    private readonly IServiceManager _serviceManager;

    public CategoriesMenuViewComponent(IServiceManager serviceManager)
    {
        _serviceManager = serviceManager;
    }

    public IViewComponentResult Invoke()
    {
        var categories = _serviceManager.CategoryService.GetAllCategories(false);
        return View(categories);
    }
}

Store/Store.APP/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Repositories;
using Store.Repositories.Contracts;
using Store.Services.Contracts;

namespace Store.APP.Controllers
{
    public class ProductController : Controller
    {
        private readonly IServiceManager _serviceManager;

        public ProductController(IServiceManager serviceManager)
        {
            _serviceManager = serviceManager;
        }

        public IActionResult Index()
        {
            var model = _serviceManager.ProductService.GetAllProducts(false);
            return View(model);
        }

        public IActionResult Get([FromRoute(Name = "id")] int id)
        {
            var product = _serviceManager.ProductService.GetOneProduct(id, false);
            return View(product);
        }


    }
}

Store/Store.APP/Views/Product/Get.cshtml
@using Store.APP.Infrastructure.Extensions
@model Product

<div class="row">
    <div class="col-md-12">
        <div class="text-center">
            <h6 class="display-6">
                @Model.Name
            </h6>

            <img class="img-fluid shadow rounded-3 p-5 my-3" src="@Model?.ImageUrl" alt="@Model.Name" />

            <p class="lead text-danger">@Model.Price.ToString("c")</p>
        </div>
    </div>
</div>


<div class="text-center">
    <div class="btn-group">
        <a class="btn btn-outline-secondary" asp-controller="Home" asp-action="Index">
            <i class="fa-solid fa-house"></i>
            Home</a>
        <form id="@Model.Id" asp-page="/cart" method="post">
            <input type="hidden" asp-for="Id" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <button type="submit" class="btn btn-outline-secondary rounded-0">
                <i class="fa fa-cart-plus"></i>
                Add To Cart
            </button>
        </form>
        <a class="btn btn-outline-secondary" asp-controller="Product" asp-action="Index">
            <i class="fa-solid fa-list"></i>
            Products</a>
    </div>
</div>

@section Header{
    <div>
        Header for only Get
    </div>
}

Store/Store.APP/Views/Product/Index.cshtml
@model IEnumerable<Product>

<div class="row">
    <div class="col-md-3">
        @await Component.InvokeAsync("CategoriesMenu")
    </div>
    <div class="col-md-9">
        <div class="row my-3">
            @foreach (var prd in Model)
            {
                <partial name="_ProductCard" model="@prd"/>
            }
        </div>
    </div>
</div>


@section Footer
{
    <div>
        Only for Index Footer
    </div>
}

Store/Store.APP/Views/Product/ProductCard.cshtml
@model Product

<div>
    <h2>@Model.Name</h2>
    <p>@Model.Price.ToString("C")</p>
    <a class="btn btn-primary" asp-action="Get" asp-route-id="@Model.Id">Get Details</a>
    <hr>
</div>

<div class="col-sm-12 col-md-4 col-lg-3 my-3">
    <div class="card" style="width: 18rem;">
        <img src="/image/default.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">@Model.Name</h5>
            <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card’s
                content.</p>
            <a class="btn btn-primary" asp-action="Get" asp-route-id="@Model.Id">
                <i class="fa-solid fa-arrow-right"></i> Get Details
            </a>
        </div>
    </div>
</div>

Store/Store.APP/Views/Product/_ProductCard.cshtml
@using Store.APP.Infrastructure.Extensions
@model Product

<div class="col-sm-12 col-md-4 my-2">
    <div class="card" style="width: 18rem;">
        <div class="card-header text-center">
            @Model.Name
        </div>

        <img src="@Model?.ImageUrl" class="card-img-top" alt="...">

        <div class="card-body">
            <div class="card-text">
                <div class="text-danger text-center lead p-2 rounded-2">
                    @Model?.Price.ToString("C2")
                </div>
            </div>
            
            <p class="card-text">@Model?.Summary</p>
            <div class="d-flex justify-content-center">
                <div class="btn btn-group">
                    <a asp-controller="Product" asp-action="Get" asp-route-id="@Model.Id"
                       class="btn btn-outline-secondary rounded-2">
                        <i class="fa-solid fa-arrow-right"></i>
                    </a>
                    <form id="@Model.Id" asp-page="/cart" method="post">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
                        <button type="submit" class="btn btn-outline-secondary mx-1">
                            <i class="fa fa-cart-plus"></i>
                        </button>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>